/**
 * AUTOGEN COMPONENTS
 * 
 * This directory contains components generated by the Self-Evolution Protocol.
 * Files here are created at runtime when evolutions are deployed.
 * 
 * Vite HMR will automatically pick up new files.
 */

// Dynamic registry of autogenerated components
export const AutogenRegistry: Record<string, React.LazyExoticComponent<any>> = {};

// This file will be updated as new components are deployed
export const AUTOGEN_MANIFEST: { id: string; fileName: string; deployedAt: number }[] = [];
